# Generated by Django 4.2.6 on 2023-12-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='longitude',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
