# Generated by Django 4.2.6 on 2023-12-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_comment_feedback_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='password',
        ),
        migrations.AddField(
            model_name='sign',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sign',
            name='Email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
